services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    _instanceof:
        Troytft\DataMapperBundle\DataTransformer\DataTransformerInterface:
            tags: [!php/const Troytft\DataMapperBundle\DependencyInjection\Compiler\DataTransformerCompilerPass::TAG]

    Troytft\DataMapperBundle\Manager: ~

    Troytft\DataMapperBundle\DataTransformer\:
        resource: '../../DataTransformer/*'
    
